/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

export class Constants {
  static readonly FULL_WIDTH = '100%';
  static readonly HALF_WIDTH = '50%';
  static readonly CENTER_HEIGHT = 200;
  static readonly CENTER_WIDTH = '85%';
  static readonly BUTTON_HEIGHT = '20%';
  static readonly LAYOUT_WEIGHT = 1;
  static readonly FONT_COLOR = '#FF007DFF';
  static readonly BLUE_COLOR = 'rgb(10, 89, 247)';
  static readonly SPACE = 8;
  static readonly TOP_MARGIN = 24;
  static readonly TOP_MARGIN_TWO = 13;
  static readonly BOTTOM_MARGIN = 16;
  static readonly BIG_FONT = 18;
  static readonly SMALL_FONT = 16;
  static readonly DIVIDER_HEIGHT = 32;
  static readonly DIALOG_HEIGHT = '42%';
  static readonly DIALOG_WIDTH = '91%';
  static readonly RADIUS = 25;
  static readonly ZERO = 0;
  static readonly ONE = 1;
  static readonly PADDING = 8;
  static readonly CURRENT_MONTH = 12;
  static readonly CURRENT_DAY = 30;
  static readonly MAX_HOUR = 23;
  static readonly MAX_MINUTE = 59;
  static readonly FOUR_HUNDRED = 400;
  static readonly ONE_HUNDRED = 100;
  static readonly FOUR = 4;
}